services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 128M
    networks:
      - pastebin
  rabbitmq:
    image: rabbitmq:3.12
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
    networks:
      - pastebin
    ports:
      - "5672:5672"
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=pastebin
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - pastebin
    ports:
      - "3306:3306"
  mongo-retrieval-replica:
    image: mongo:6.0
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]
    environment:
      - MONGO_INITDB_DATABASE=pastebin
    ports:
      - "27018:27017"
    volumes:
      - mongo-retrieval-replica-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
    networks:
      - pastebin
  create-service-1:
    build: ../../create-service
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512M
    environment:
      - PORT=8085
      - MYSQL_DSN=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mysql:3306)/pastebin?parseTime=true
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - pastebin
    ports:
      - "8085:8085"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.create-service.rule=PathPrefix(`/api/pastes`) && Method(`POST`)"
      - "traefik.http.routers.create-service.entrypoints=web"
      - "traefik.http.services.create-service.loadbalancer.server.port=8085"
  retrieval-service-1:
    build: ../../retrieval-service
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    environment:
      - PORT=8081
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - REDIS_URI=${REDIS_URI}
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongo-retrieval-replica
      - rabbitmq
    networks:
      - pastebin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.retrieval-service.entrypoints=web"
      - "traefik.http.services.retrieval-service.loadbalancer.server.port=8081"
      - "traefik.http.routers.retrieval.rule=PathRegexp(`/api/pastes/{url}/(content|policy)`) && Method(`GET`)"
volumes:
  rabbitmq-data:
  mysql-data:
  mongo-retrieval-replica-data:
networks:
  pastebin:
    driver: bridge
