http:
  routers:
    create-service-router:
      rule: "PathPrefix(`/api/pastes`) && Method(`POST`)"
      service: create-service
      entryPoints:
        - web

    retrieval-service-router:
      rule: "PathRegexp(`/api/pastes/{url}/(content|policy)`) && Method(`GET`)"
      service: retrieval-service
      entryPoints:
        - web

  services:
    create-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.110:8085"
          - url: "http://192.168.1.112:8081"

    retrieval-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.110:8081"
          - url: "http://192.168.1.112:8082"
