http:
  routers:
    create:
      rule: "PathPrefix(`/api/pastes`) && Method(`POST`)"
      service: create-service
      entryPoints:
        - web
    retrieval:
      rule: "PathRegexp(`/api/pastes/{url}/(content|policy)`) && Method(`GET`)"
      service: retrieval-service
      entryPoints:
        - web
    analytics:
      rule: "PathRegexp(`/api/analytics/(hourly|weekly|monthly)/{pasteUrl}`) || PathRegexp(`/api/pastes/{url}/stats`) && Method(`GET`)"
      service: analytics-service
      entryPoints:
        - web
    cleanup:
      rule: "PathPrefix(`/api/cleanup`)"
      service: cleanup-service
      entryPoints:
        - web
  services:
    create-service:
      loadBalancer:
        servers:
          - url: "http://create-service-1:8080"
          - url: "http://192.168.1.112:8080"
    retrieval-service:
      loadBalancer:
        servers:
          - url: "http://retrieval-service-1:8081"
            weight: 1
          - url: "http://192.168.1.112:8081"
            weight: 3
    analytics-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.113:8082"
    cleanup-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.113:8083"
entryPoints:
  web:
    address: ":80"